import Head from 'next/head'
import Layout from '../components/Layout'
import Image from 'next/image'
import Link from 'next/link'

import { Hero } from '../components/Hero'
import { Features } from '../components/Features'
import { table, minifyItems } from "../utils/Airtable";
import HomeJobCard from '../components/HomeJobCard'

const Home=({featuredJobs})=> {
  console.log(featuredJobs)
  return (
   
    <div className="bg-background1">
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
     <Hero/>  
     <Features/>
     
      <div className="flex justify-center"> 
      <h2 className="text-white text-3xl">Featured Jobs</h2>
      
        </div>
        <div className="flex items-center justify-center w-screen min-h-screen p-10">
      
        <div className="grid xl:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-2 max-w-6xl " >
        {featuredJobs.map(jobitem=>(
        
        <HomeJobCard jobitem={jobitem} key={jobitem.id}/>
       
    ))}
      <div className="flex flex-col bg-gradient-to-r from-gradientbase1 to-accent1 rounded-lg p-2 m-2">
            <div  className=" flex justify-items-center  items-center space-x-4 relative ">
            
            
           <div>
          
          
            </div>
            </div>
            <Link href='/jobs'>
                <div className="flex flex-col items-start mt-2  m-5 rounded cursor-pointer">
                 
                    <h4 className=" text-lg font-semibold">See All Jobs👉</h4>
                   
                   
               
                </div>
                </Link>
                </div>
      </div>

      </div>
      </div>
    </div>
   
  ) }

  export async function getStaticProps() {
    try {
      const jobsData = await table.select({ view: 'Approved View', maxRecords: 7, sort: [
        {field: 'Approved', direction: 'desc'},{field: 'Created time', direction: 'desc'}
       
    ]}).firstPage();
      return {
        props: {
          featuredJobs: minifyItems(jobsData),
          revalidate:1
        },
      };
    } catch (error) {
      console.log(error);
      return {
        props: {
          err: "Something went wrong 😕",
        },
      };
    }
  }

 
export default Home;
